void q3(int arr[],int n);
void q4(int length,...);
int q5(int arr1[],int n1,int arr2[],int n2);
void q6(int A[],int sizeA,int B[],int sizeB);
int q7(const int arr[],int n);
void q8(int arr[],int n);
void q8Helper(int arr[],int n);
void q9(int arr[],int n);
int max(int arr[],int n);
int min(int arr[],int n);
void swap(int arr[],int index);
void printArray(int arr[],int n);
